---
title: "James Bell CV MRC LID"
author: James Bell
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> jbell403@gmail.com
- <i class="fa fa-phone"></i> +447821142059
<!-- - <i class="fa fa-github"></i> [github.com/jamesbell1991](https://github.com/jamesbell1991) -->
- <i class="fa fa-twitter"></i> [jamesbell1991](https://twitter.com/jamesbell91)
- <i class="fa fa-linkedin"></i> [James Bell](https://uk.linkedin.com/public-profile/in/james-bell-45552723)
- Location: London, UK


Skills {#skills}
--------------------------------------------------------------------------------

- Proficiency in Microsoft programs (Word, Excel, PowerPoint, Outlook)

- Software: R, STATA, Nvivo, SPSS

- Languages: French (advanced), Russian (advanced), Spanish (intermediate), Polish (basic)


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

<!-- This CV was made with the R package [**pagedown**](https://github.com/rstudio/pagedown). -->

<!-- Last updated on `r format(Sys.Date(), "%B %d %Y")`. -->



Main
================================================================================

James Bell {#title}
--------------------------------------------------------------------------------

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### London School of Hygiene and Tropical Medicine

MSc Epidemiology

N/A

2019-21

*Core modules*: Foundational courses in epidemiology and statistics, Advanced Statistical Methods in Epidemiology, Epidemiology in Practice, Clinical Trials, Study Design, Epidemiology and Control of Infectious Diseases, Infectious Disease Modelling

*Supplementary modules*: Epidemiology and -omics, Demographic Methods, Advanced Research Methods (including Big Data, causal inference and working with Electronic Medical Records)

*Working project title*: The Impact of COVID-19 on the Probablity of Measles Outbreaks in Nigeria. 


### University of Glasgow

MSc Russian, Central and East European Studies

N/A

2013-14
Distinction

Dissertation title: Representations of HIV/AIDS in Polish Public Discourse

### Corpus Christi College, University of Cambridge

MA (Hons) Modern and Medieval Languages

N/A

2009-13
1st class

French and Russian


Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Associate Director

Global Health Unit, Ipsos MORI

London, UK

2014-

Qualitative and quantitative researcher leading studies on behalf of NGOs, governments and industry to inform strategy and intervention design. Responsibilities include:


- Preparing concept notes and grant applications, including costing and work planning   
- Writing IRB protocols and managing submissions
- Literature reviews, qualitative and quantitative material development, complex sample design, interviewer training, survey implementation and fieldwork monitoring (including in Nigeria, Uganda, Bangladesh, India, Zambia, Zimbabwe, South Africa, Malawi, Guinea and Kenya) and data management   
- Analysis using behavioural science frameworks and statistical modelling 
- Report preparation and results dissemination (including presentations, webinars and peer-reviewed publications)
- Collaboration with donor, government and NGO partners for research and stakeholder consultation activties
- Line management of two Senior Researchers


::: aside
**Example Projects**  
*Vaccination Uptake in 3 African Countries*: Programme of research in Nigeria, Uganda and Guinea to understand community, family and individual-level determinants of early childhood vaccination uptake to inform BMGF and partners' programmatic activties and future intervention design

*Test & Treat South Africa*: Multi-stage project to understand barriers to HIV testing and treatment initiation among young men in South Africa to design appropriate interventions. [Featured in 2018 UNAIDS Report](https://www.unaids.org/sites/default/files/media_asset/jc2940_knowledge-is-power-report_en.pdf). Led to the [Coach Mpilo Intervention](https://www.psi.org/2020/06/coach-mpilo/)
:::


Publications & Presentations {data-icon=file}
--------------------------------------------------------------------------------
### Targeting interventions for HIV testing and treatment uptake: an attitudinal and behavioural segmentation of men aged 20-34 in KwaZulu-Natal and Mpumalanga, South Africa 

Peer reviewed article, PLOS ONE (revise and resumbit)

N/A

2020

**Bell J**, Sharma S, Malone S, Levy M, Reast J, Ciecielag J, Gogolina S, Ansons T, Fourie S, Braz R, Little K, Hasen N


### Understanding barriers to HIV testing and treatment: a study of young men and healthcare providers in KwaZulu-Natal and Mpumalanga

Peer-reviewed article, South African Health Review [[Link]](https://www.hst.org.za/publications/South%20African%20Health%20Reviews/11%20SAHR_2019_Understanding%20barriers%20to%20HIV%20testing%20and%20treatment.pdf)

N/A

2019

**Bell J**, Sharma S, Malone S, Levy M, Reast J, Little K, Hasen N


### Attitudinal, situational and behavioural factors affecting ARV initiation among newly diagnosed HIV+ men aged 20-34 in Mpumalanga and KwaZulu-Natal, South Africa

Presentation at AIDS Impact 2019 (Presenting author)

London

2019

**Bell J**, Sharma S, Hasen N, Malone S

### Awareness of PrEP and Drivers and Barriers to Use Among Men Aged 20-34 in Mpumalanga and KwaZulu-Natal, South Africa

Poster at IAS 2019

Mexico City

2019

**Bell J**, Sharma S, Hasen N, Malone S

### Assessment of Dietary Intake Capture Methods in Three Large-Scale Surveys

Presentation at International Conference on Food Security and Nutrition (Presenting author)

Barcelona

2019

Sharma S, **Bell J**, Bates S, Robinson R

Additional Courses and Training {data-icon=rocket}
--------------------------------------------------------------------------------
### Microbiology

University of California San Diego Extension, 4 units

N/A

2020

### Applied Immunology 

University of California San Diego Extension, 3 units

N/A

2020

### TRREE Research Ethics Training 

N/A

N/A

2017 

### Advanced Certificate in Market and Social Research Practice 
Market Research Society. Subsequently tutor and examiner for 2018-2019 assessment rounds

N/A

2016


